spring.application.name=Code-Review-Assistant-AI

spring.datasource.url=jdbc:mysql://localhost:3306/AicodeReview
spring.datasource.username=root
spring.datasource.password=Prashu@2004

spring.jpa.hibernate.ddl-auto=update

openai.api.key=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
